import { Heart, Users, Briefcase, Star } from "lucide-react";

export default {
  features: [
    {
      badge: "AI-Powered",
      title: "Deep AI Insights",
      description: "Leverage advanced AI models trained on thousands of palm reading patterns for entertaining interpretations.",
    },
    {
      badge: "Private",
      title: "Your Data Stays Safe",
      description: "Your palm images are never stored — processed securely and deleted immediately after reading.",
    },
    {
      badge: "Instant",
      title: "Lightning Fast Results",
      description: "Get your personalized palm reading in seconds with our optimized AI processing.",
    },
    {
      badge: "Fun",
      title: "Entertainment Focused",
      description: "Designed for enjoyment and curiosity - perfect for parties, conversations, and personal exploration.",
    },
    {
      badge: "Free",
      title: "Always Free to Use",
      description: "No hidden costs, no subscriptions - unlimited palm readings for everyone to enjoy.",
    },
    {
      badge: "Easy",
      title: "Simple Upload Process",
      description: "Just take a photo of your palm and upload - no complicated steps or technical knowledge required.",
    }
  ],
  
  readingTypes: [
    {
      icon: Heart,
      title: "Love & Relationships",
      description: "Discover insights about your love life, compatibility, and relationship patterns through your heart line.",
      color: "text-red-500",
      bgColor: "bg-red-100 dark:bg-red-900/30"
    },
    {
      icon: Briefcase,
      title: "Career & Success",
      description: "Explore your professional path, talents, and opportunities for growth through your fate line.",
      color: "text-blue-500",
      bgColor: "bg-blue-100 dark:bg-blue-900/30"
    },
    {
      icon: Users,
      title: "Personality Traits",
      description: "Understand your character, strengths, and areas for personal development through palm analysis.",
      color: "text-green-500",
      bgColor: "bg-green-100 dark:bg-green-900/30"
    },
    {
      icon: Star,
      title: "Life Path & Destiny",
      description: "Get entertaining guidance on your journey, potential adventures, and life's possibilities.",
      color: "text-purple-500",
      bgColor: "bg-purple-100 dark:bg-purple-900/30"
    }
  ],

  palmLines: [
    {
      name: "Heart Line",
      description: "Reveals insights about emotions, relationships, and romantic tendencies",
      interpretation: "love and emotional connections"
    },
    {
      name: "Head Line",
      description: "Shows thinking patterns, intelligence, and decision-making style",
      interpretation: "mental approach and wisdom"
    },
    {
      name: "Life Line",
      description: "Indicates vitality, major life changes, and general well-being",
      interpretation: "life energy and major events"
    },
    {
      name: "Fate Line",
      description: "Suggests career path, life direction, and external influences",
      interpretation: "destiny and life purpose"
    }
  ],

  disclaimers: {
    main: "This website is created purely for entertainment and fun purposes. Do not rely on palm readings for making important life decisions.",
    scientific: "We make no claims about scientific accuracy or evidence-based results. HastAI does not take responsibility for any decisions made based on our readings.",
    advice: "Palm reading results are generated by AI for entertainment only and should not be considered as professional advice, medical guidance, or factual predictions about your future.",
    age: "This service is intended for users 13 years and older. Minors should use this service with parental guidance."
  },

  funFacts: [
    "Palm reading, also known as chiromancy, has been practiced for over 5,000 years!",
    "Did you know? Your dominant hand shows your present and future, while your non-dominant hand reveals your past and natural traits.",
    "Ancient civilizations like the Greeks, Romans, and Chinese all had their own palm reading traditions.",
    "There are over 100 different markings and lines that traditional palmists look for on hands.",
    "Modern palm reading is purely for entertainment - but it's still a fun way to spark conversations!"
  ],

  appInfo: {
    name: "HastAI",
    tagline: "AI-Powered Palm Reading for Fun",
    description: "Experience the ancient art of palmistry with modern AI technology",
    version: "1.0.0",
    purpose: "Entertainment and educational exploration of palmistry traditions"
  }
}